version: '3'

services:
  web:
    build: .
    command: gunicorn formulario_professores.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - celery-beat

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A setup worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A setup beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
