version: '3'

services:
  web:
    build: .
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --max-requests 1000
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - redis
      - celery
      - celery-beat

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A setup worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A setup beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery


