"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-imd7n1@2kq3=5*&$@*a)coc-mr@%h-(*jr&a_-h9qp817a(d(c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'formulario.gabrielsouzadev.com', 'localhost', '15.229.6.119', 'cannon.nexusautomate.com.br']

CSRF_TRUSTED_ORIGINS = [
    "http://cannon.nexusautomate.com.br",
    "https://cannon.nexusautomate.com.br",
]

# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'formulario_professores'
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'disparo_mensagens',  # Nome do seu banco de dados
        'USER': 't3a',  # Usuário do banco
        'PASSWORD': '@t3a1234@',  # Senha do banco
        'HOST': 'db',  # Se for Docker, pode ser o nome do container
        'PORT': '5432',  # Porta padrão do PostgreSQL
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # <- Aqui é onde os arquivos serão coletados
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/mensagens/'  # Após o login bem-sucedido, redirecionar para a página de listagem de aulas
LOGOUT_REDIRECT_URL = '/login/'  # Após o logout, redirecionar para a página de login

#Celery
CELERY_BROKER_URL = 'redis://redis:6379/0'  # Verifique se o Redis está rodando nessa URL
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'


CELERY_BEAT_SCHEDULE = {
    'disparar_mensagens': {
        'task': 'formulario_professores.tasks.verificar_disparos',
        'schedule': crontab(minute='*'),  # Executa todos os dias à oito horas da manhã
    },
}

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

#Z-API
ZAPI_INSTANCE_ID = '3DE195BC07E241D736992A8D0B892839'
ZAPI_TOKEN = '82861221A5071FE5B9F1F222'
ZAPI_CLIENT_TOKEN = 'Fcf0d9d77aa9f4050b3988369b52f6dfbS'

ZAPI_PARTNER_TOKEN='eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjQ4OTQzNzE4MjksInN1YiI6InQzYWNvbnRhY3RAZ21haWwuY29tIiwiaXNzIjoiZW1GaGNDMXpaV04xY21sMGVTMWhjR2s9IiwiYXVkIjoiZW1GaGNDMWhjR2s9IiwiZXhwIjo0ODk0MzcxODI5LCJvbkRlbWFuZCI6dHJ1ZSwicm9sZSI6IkVOVEVSUFJJU0UiLCJpbnRlZ3JhdG9yIjp0cnVlLCJ0ZW5hbnRPd25lciI6IlpXMWhhV3hBWm05MWNuQnBlR1ZzTG1sMCJ9.gC2Rvk6-2CRrvLV3EB1ifFP-P7an2Qq42EreJrqr8Mo'